spring:
  datasource:
    # url: jdbc:mysql://localhost:3306/member?userSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    # url: jdbc:mysql://dessert-db:3306/member?userSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    # username: root
    # password: '{cipher}AQAeDtv5DcgoyuaEtKp4+VkBHqcMmI21aSV5ShWhfIM6nZVhCNUzxZmLji039e7PbIMXLNgEcc90lnr/tZulZbgCJYdOYoYvV8TaI6GUtK8hEXUxOp64igwn8fUgVXOhHAPnqcfxtLAb6O5YXtX2hYEKTycB+q+ySXnusE2fkNDaHltU3mxYvoMO/WGv+Wn6RvODctdLutn8atYBj179fcN1JPakhpmT2i1NkfoqOnhBQROmwVvbyNwaPI7r0ywB+pp0zJHwnHGUiUD0Dn7qwRW5oq60RXsRC69FAUq2a/XIj8X+TLBF39wlVcUT1ex0luaFoo8fU5sRNEUuK9Q0+UdEt+x+tIlKduFZZhXs3aN0l9vTDNf+EeTTOIJHN9eZMng='
    url: jdbc:mysql://dessert-db.cfm2a6qgmjgw.ap-northeast-2.rds.amazonaws.com:3306/member?userSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: '{cipher}AQBB3uesvhTgWbkiVm4RNp8kqd63ms8cNhCal2332frigni8jnOX6YzsGad0BIQYM0Blag9EENKYKY18YC/OGoPUOAr4DSsN+1JNhls7h9LWGodkAPG4oNgzxTGyQF++b/XjQdgsvfoRhY8xA3Lh76KzK0ciu7MA1683KFOmfJ16AdHndKTeDjPnqx7WUa1CQi0EeZZ3orx4LOKw7dBIcIz+N1Q8iZhteA1vBSl9JdROZ1lKVKC7i0lM4USH/I61OpasAMqholPJpx0YZ56tiBfUL/GnalCYnyNRIQro7QW6NJAF4bRI19uMd5RjRWlpEokuzvDXdKvz3D3bl2CGe5zVJLnECqgqoMTT1ACFn3huTlkgOKztZzohtMxzel1lW+c='

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  redis:
    # host: localhost
    host: redis
    port: 6379
  jwt:
    secret: '{cipher}AQBpayL+t4uQ9XbKpr53Gawm2bzZyGtEeZcAcBrfL4yUr/ku5pxqsS10PKYgCfqaK4lhhR4VNBf55I1wisrmNaZQc9I4T0Gi6a4IM0loTsZD9Uy9aWFgNkRq9RcKtPq8n/SM4VF0hTDYCEHdwVTRP+xxIeif9upLpbavk6sxw1wLfnFrJpkZR+kKEql6aUmG0hFvvAfmwROe9gwFUA7f1CGTsfP/CkqlYF6G44NqhwWwous7qSTKMrl6wMRKUnTukG7vygeWKh0qHhCY7ZsXRF1IuGtzMapN9isyMvnXloFtck7vbClif5jJtl6YuSq27Wwn9GLyhugeFmSzL1eHLpciQUfHIpE9WpBH9it5OFEWmd3rSNRdiUWaKQeaVdkoPoerUIqHWGZno7vCJeSKnybkPrugnrlci4A1b3Ub2dmhfjpGr1fD+FtewTFiknqJ0dQzUFrPc4DH0F3sNFBqkLLgOO4FlfwrrmXW3SGJFoWxnQWQctQjgFNaBavgm8Q6LyrTdvz/cHRSliKJ/ya9OCD4YiWo/ia2/abG21sfFHiyjg=='
