spring:
  datasource:
    url: jdbc:mysql://localhost:3306/member?userSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    # url: jdbc:mysql://dessert-db:3306/member?userSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: '{cipher}AQAeDtv5DcgoyuaEtKp4+VkBHqcMmI21aSV5ShWhfIM6nZVhCNUzxZmLji039e7PbIMXLNgEcc90lnr/tZulZbgCJYdOYoYvV8TaI6GUtK8hEXUxOp64igwn8fUgVXOhHAPnqcfxtLAb6O5YXtX2hYEKTycB+q+ySXnusE2fkNDaHltU3mxYvoMO/WGv+Wn6RvODctdLutn8atYBj179fcN1JPakhpmT2i1NkfoqOnhBQROmwVvbyNwaPI7r0ywB+pp0zJHwnHGUiUD0Dn7qwRW5oq60RXsRC69FAUq2a/XIj8X+TLBF39wlVcUT1ex0luaFoo8fU5sRNEUuK9Q0+UdEt+x+tIlKduFZZhXs3aN0l9vTDNf+EeTTOIJHN9eZMng='

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  jwt:
    secret: '{cipher}AQBtfpf2oaSWZZVRYFS4BFym9spJ8w2p4paKciXy5fNw/sihaMz1ZxpmtBR2TFMgQSecmc3rdaiXtpxW7HwQnxdt8lHw2QDnm/dWAfoWKsyNroSzgkCri/sNVjXa9sLK7EbfZph+JM4/FXgSQDP+MM7hJRZFPTloR51+HNearQ++U7Jy2+jqOKbfqZj7cz9xjPCoD1pm0ATqpCQZg7Vwoig6rB3FBUeoHNJbZ8QwM0VXPJWCP4zuO82v2I5QznnwCavUKboolqnTM/hqLptVXuLOLI/k9LIxxv8C0wjwk9XEt8+5LZ7tAMdK+/vCf2Xpt8PNMjTIfesTfnaYevShTCLlj8gKBt8qK2Q6q+QJveSbUjzsmfSBx6CldrcyCv4j9LfDOIG3LjpYIsUvsiBLSzdlDSc/dqllKe/Ng1aufSUzBw7CogXJJ4X04TCUbpzBLlFcMFRWbvl23fCUcEPAczFJR5xi1Q1IToHT0UR0L4Kp6Xy9gRyoZXrAYojWXAkl1dE='
